export const TRANSACTION_LIST = [
    {
        "FName": "FMemberA",
        "Date": "01-04-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 1,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-04-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 999999,
        "type": "Earning",
        "id": 2,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-04-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 3,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-05-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 4,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-05-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 5,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-05-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 6,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-06-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 7,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-06-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 8,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-06-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 9,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-07-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 10,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-07-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 11,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-07-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 12,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-08-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 13,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-08-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 14,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-08-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 15,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "20-08-2020",
        "subtype": "MF Sale",
        "accountId": 334455,
        "Gross amount": 100000,
        "Tax amount": 30000,
        "amount": 70000,
        "type": "Earning",
        "id": 16,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-09-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 17,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-09-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 18,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-09-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 19,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-10-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 20,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-10-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 21,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-10-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 22,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-11-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 23,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-11-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 24,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-11-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 25,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-12-2020",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 26,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-12-2020",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 27,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-12-2020",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 28,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-01-2021",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 29,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-01-2021",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 30,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-01-2021",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 31,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-02-2021",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 32,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-02-2021",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 33,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-02-2021",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 34,
        "mode": "Account"
    },
    {
        "FName": "FMemberB",
        "Date": "15-02-2021",
        "subtype": "Property Sale",
        "accountId": 228899,
        "Gross amount": 500000,
        "Tax amount": 150000,
        "amount": 350000,
        "type": "Earning",
        "id": 35,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "01-03-2021",
        "subtype": "Pension",
        "accountId": 112233,
        "Gross amount": 26000,
        "Tax amount": 7800,
        "amount": 18200,
        "type": "Earning",
        "id": 36,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "01-03-2021",
        "subtype": "Salary",
        "accountId": 332211,
        "Gross amount": 150000,
        "Tax amount": 45000,
        "amount": 105000,
        "type": "Earning",
        "id": 37,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "01-03-2021",
        "subtype": "Salary",
        "accountId": 445566,
        "Gross amount": 90000,
        "Tax amount": 27000,
        "amount": 63000,
        "type": "Earning",
        "id": 38,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "25-03-2021",
        "subtype": "SB Interest",
        "accountId": 112233,
        "Gross amount": 1200,
        "Tax amount": 360,
        "amount": 840,
        "type": "Earning",
        "id": 39,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "25-03-2021",
        "subtype": "SB Interest",
        "accountId": 115566,
        "Gross amount": 1500,
        "Tax amount": 450,
        "amount": 1050,
        "type": "Earning",
        "id": 40,
        "mode": "Account"
    },
    {
        "FName": "FMemberB",
        "Date": "25-03-2021",
        "subtype": "SB Interest",
        "accountId": 228899,
        "Gross amount": 3300,
        "Tax amount": 990,
        "amount": 2310,
        "type": "Earning",
        "id": 41,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "25-03-2021",
        "subtype": "SB Interest",
        "accountId": 334455,
        "Gross amount": 4500,
        "Tax amount": 1350,
        "amount": 3150,
        "type": "Earning",
        "id": 42,
        "mode": "Account"
    },
    {
        "FName": "FMemberC",
        "Date": "25-03-2021",
        "subtype": "SB Interest",
        "accountId": 332211,
        "Gross amount": 1500,
        "Tax amount": 450,
        "amount": 1050,
        "type": "Earning",
        "id": 43,
        "mode": "Account"
    },
    {
        "FName": "FMemberD",
        "Date": "25-03-2021",
        "subtype": "SB Interest",
        "accountId": 445566,
        "Gross amount": 6000,
        "Tax amount": 1800,
        "amount": 4200,
        "type": "Earning",
        "id": 44,
        "mode": "Account"
    },
    {
        "FName": "FMemberA",
        "Date": "05-Apr-20",
        "subType": "Equity",
        "type": "Investment",
        "amount": 12500,
        "accountId": 115566,
        "id": 45
    },
    {
        "FName": "FMemberC",
        "Date": "10-Apr-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 46
    },
    {
        "FName": "FMemberD",
        "Date": "15-Apr-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 47
    },
    {
        "FName": "FMemberC",
        "Date": "10-May-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 48
    },
    {
        "FName": "FMemberD",
        "Date": "15-May-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 49
    },
    {
        "FName": "FMemberC",
        "Date": "10-Jun-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 50
    },
    {
        "FName": "FMemberD",
        "Date": "15-Jun-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 51
    },
    {
        "FName": "FMemberC",
        "Date": "10-Jul-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 52
    },
    {
        "FName": "FMemberD",
        "Date": "15-Jul-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 53
    },
    {
        "FName": "FMemberC",
        "Date": "10-Aug-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 54
    },
    {
        "FName": "FMemberD",
        "Date": "15-Aug-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 55
    },
    {
        "FName": "FMemberA",
        "Date": "05-Sep-20",
        "subType": "Equity",
        "type": "Investment",
        "amount": 7300,
        "accountId": 115566,
        "id": 56
    },
    {
        "FName": "FMemberC",
        "Date": "10-Sep-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 57
    },
    {
        "FName": "FMemberD",
        "Date": "15-Sep-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 58
    },
    {
        "FName": "FMemberC",
        "Date": "10-Oct-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 59
    },
    {
        "FName": "FMemberD",
        "Date": "15-Oct-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 60
    },
    {
        "FName": "FMemberC",
        "Date": "10-Nov-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 61
    },
    {
        "FName": "FMemberD",
        "Date": "15-Nov-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 62
    },
    {
        "FName": "FMemberA",
        "Date": "05-Dec-20",
        "subType": "Equity",
        "type": "Investment",
        "amount": 6400,
        "accountId": 115566,
        "id": 63
    },
    {
        "FName": "FMemberC",
        "Date": "10-Dec-20",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 64
    },
    {
        "FName": "FMemberD",
        "Date": "15-Dec-20",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 65
    },
    {
        "FName": "FMemberC",
        "Date": "10-Jan-21",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 66
    },
    {
        "FName": "FMemberD",
        "Date": "15-Jan-21",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 67
    },
    {
        "FName": "FMemberC",
        "Date": "10-Feb-21",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 68
    },
    {
        "FName": "FMemberD",
        "Date": "15-Feb-21",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 69
    },
    {
        "FName": "FMemberB",
        "Date": "20-Feb-21",
        "subType": "Fixed Deposit",
        "type": "Investment",
        "amount": 500000,
        "accountId": 228899,
        "id": 70
    },
    {
        "FName": "FMemberA",
        "Date": "05-Mar-21",
        "subType": "Equity",
        "type": "Investment",
        "amount": 8000,
        "accountId": 115566,
        "id": 71
    },
    {
        "FName": "FMemberC",
        "Date": "10-Mar-21",
        "subType": "MF SIP",
        "type": "Investment",
        "amount": 15000,
        "accountId": 334455,
        "id": 72
    },
    {
        "FName": "FMemberD",
        "Date": "15-Mar-21",
        "subType": "Recurring Deposit",
        "type": "Investment",
        "amount": 20000,
        "accountId": 445566,
        "id": 73
    },
    {
        "FName": "FMemberA",
        "Date": "25-Mar-21",
        "subType": "Fixed Deposit",
        "type": "Investment",
        "amount": 100000,
        "accountId": 115566,
        "id": 74
    },
    {
        "FName": "FMemberC",
        "Date": "05-Apr-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 75
    },
    {
        "FName": "FMemberC",
        "Date": "05-Apr-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 76
    },
    {
        "FName": "FMemberA",
        "Date": "05-Apr-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 2000,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 77
    },
    {
        "FName": "FMemberB",
        "Date": "05-Apr-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 2400,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 78
    },
    {
        "FName": "FMemberC",
        "Date": "10-Apr-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 4890,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 79
    },
    {
        "FName": "FMemberC",
        "Date": "10-Apr-20",
        "accountId": 332211,
        "aa": "Fuel",
        "aaa": "Car",
        "amount": 2560,
        "Mode of Payment": "Credit Card",
        "subType": "Fuel - Car",
        "type": "Expenditure",
        "id": 80
    },
    {
        "FName": "FMemberD",
        "Date": "12-Apr-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 81
    },
    {
        "FName": "FMemberE",
        "Date": "18-Apr-20",
        "accountId": "xx",
        "aa": "Fees",
        "aaa": "School",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "Fees - School",
        "type": "Expenditure",
        "id": 82
    },
    {
        "FName": "FMemberF",
        "Date": "18-Apr-20",
        "accountId": "yy",
        "aa": "Fees",
        "aaa": "School",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "Fees - School",
        "type": "Expenditure",
        "id": 83
    },
    {
        "FName": "FMemberC",
        "Date": "25-Apr-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 2100,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 84
    },
    {
        "FName": "FMemberC",
        "Date": "25-Apr-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 85
    },
    {
        "FName": "FMemberC",
        "Date": "05-May-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 86
    },
    {
        "FName": "FMemberC",
        "Date": "05-May-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 87
    },
    {
        "FName": "FMemberA",
        "Date": "05-May-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1500,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 88
    },
    {
        "FName": "FMemberB",
        "Date": "05-May-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 3250,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 89
    },
    {
        "FName": "FMemberC",
        "Date": "10-May-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5500,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 90
    },
    {
        "FName": "FMemberC",
        "Date": "12-May-20",
        "accountId": 332211,
        "aa": "Fuel",
        "aaa": "Car",
        "amount": 2400,
        "Mode of Payment": "Credit Card",
        "subType": "Fuel - Car",
        "type": "Expenditure",
        "id": 91
    },
    {
        "FName": "FMemberD",
        "Date": "12-May-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 92
    },
    {
        "FName": "FMemberE",
        "Date": "18-May-20",
        "accountId": "xx",
        "aa": "Books",
        "aaa": "School",
        "amount": 2000,
        "Mode of Payment": "Online Payment",
        "subType": "Books - School",
        "type": "Expenditure",
        "id": 93
    },
    {
        "FName": "FMemberF",
        "Date": "18-May-20",
        "accountId": "yy",
        "aa": "Books",
        "aaa": "School",
        "amount": 2500,
        "Mode of Payment": "Online Payment",
        "subType": "Books - School",
        "type": "Expenditure",
        "id": 94
    },
    {
        "FName": "FMemberC",
        "Date": "25-May-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1900,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 95
    },
    {
        "FName": "FMemberC",
        "Date": "25-May-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 96
    },
    {
        "FName": "FMemberC",
        "Date": "05-Jun-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 97
    },
    {
        "FName": "FMemberC",
        "Date": "05-Jun-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 98
    },
    {
        "FName": "FMemberA",
        "Date": "06-Jun-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1800,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 99
    },
    {
        "FName": "FMemberB",
        "Date": "06-Jun-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 3300,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 100
    },
    {
        "FName": "FMemberC",
        "Date": "10-Jun-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5650,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 101
    },
    {
        "FName": "FMemberD",
        "Date": "12-Jun-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 102
    },
    {
        "FName": "FMemberE",
        "Date": "18-Jun-20",
        "accountId": "xx",
        "aa": "Fees",
        "aaa": "Sports Class",
        "amount": 4500,
        "Mode of Payment": "Online Payment",
        "subType": "Fees - Sports Class",
        "type": "Expenditure",
        "id": 103
    },
    {
        "FName": "FMemberF",
        "Date": "18-Jun-20",
        "accountId": "yy",
        "aa": "Fees",
        "aaa": "Sports Class",
        "amount": 4500,
        "Mode of Payment": "Online Payment",
        "subType": "Fees -  Sports Class",
        "type": "Expenditure",
        "id": 104
    },
    {
        "FName": "FMemberC",
        "Date": "25-Jun-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1960,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 105
    },
    {
        "FName": "FMemberC",
        "Date": "25-Jun-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 106
    },
    {
        "FName": "FMemberC",
        "Date": "05-Jul-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 107
    },
    {
        "FName": "FMemberC",
        "Date": "05-Jul-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 108
    },
    {
        "FName": "FMemberA",
        "Date": "05-Jul-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 2100,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 109
    },
    {
        "FName": "FMemberB",
        "Date": "06-Jul-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 980,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 110
    },
    {
        "FName": "FMemberC",
        "Date": "10-Jul-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 7850,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 111
    },
    {
        "FName": "FMemberD",
        "Date": "12-Jul-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 112
    },
    {
        "FName": "FMemberE",
        "Date": "18-Jul-20",
        "accountId": "xx",
        "aa": "Doctor",
        "aaa": "Apollo Clinic",
        "amount": 400,
        "Mode of Payment": "Online Payment",
        "subType": "Doctor - Apollo Clinic",
        "type": "Expenditure",
        "id": 113
    },
    {
        "FName": "FMemberF",
        "Date": "18-Jul-20",
        "accountId": "yy",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 114
    },
    {
        "FName": "FMemberC",
        "Date": "18-Jul-20",
        "accountId": 332211,
        "aa": "Fuel",
        "aaa": "Car",
        "amount": 2680,
        "Mode of Payment": "Credit Card",
        "subType": "Fuel - Car",
        "type": "Expenditure",
        "id": 115
    },
    {
        "FName": "FMemberC",
        "Date": "25-Jul-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 2110,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 116
    },
    {
        "FName": "FMemberC",
        "Date": "25-Jul-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 117
    },
    {
        "FName": "FMemberC",
        "Date": "05-Aug-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 118
    },
    {
        "FName": "FMemberC",
        "Date": "05-Aug-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 119
    },
    {
        "FName": "FMemberA",
        "Date": "05-Aug-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 2150,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 120
    },
    {
        "FName": "FMemberB",
        "Date": "06-Aug-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 3250,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 121
    },
    {
        "FName": "FMemberC",
        "Date": "10-Aug-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 6940,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 122
    },
    {
        "FName": "FMemberC",
        "Date": "15-Aug-21",
        "accountId": 332211,
        "aa": "Vacation",
        "aaa": "Hill Station",
        "amount": 8400,
        "Mode of Payment": "Credit Card",
        "subType": "Vacation - Hill Station",
        "type": "Expenditure",
        "id": 123
    },
    {
        "FName": "FMemberD",
        "Date": "12-Aug-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 124
    },
    {
        "FName": "FMemberE",
        "Date": "18-Aug-20",
        "accountId": "xx",
        "aa": "Stationery",
        "aaa": "NULL",
        "amount": 120,
        "Mode of Payment": "Online Payment",
        "subType": "Stationery - NULL",
        "type": "Expenditure",
        "id": 125
    },
    {
        "FName": "FMemberF",
        "Date": "18-Aug-20",
        "accountId": "yy",
        "aa": "Stationery",
        "aaa": "NULL",
        "amount": 120,
        "Mode of Payment": "Online Payment",
        "subType": "Stationery - NULL",
        "type": "Expenditure",
        "id": 126
    },
    {
        "FName": "FMemberC",
        "Date": "25-Aug-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 2090,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 127
    },
    {
        "FName": "FMemberC",
        "Date": "25-Aug-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 128
    },
    {
        "FName": "FMemberC",
        "Date": "05-Sep-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 129
    },
    {
        "FName": "FMemberC",
        "Date": "05-Sep-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 130
    },
    {
        "FName": "FMemberA",
        "Date": "05-Sep-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1450,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 131
    },
    {
        "FName": "FMemberB",
        "Date": "06-Sep-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 2560,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 132
    },
    {
        "FName": "FMemberC",
        "Date": "10-Sep-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5630,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 133
    },
    {
        "FName": "FMemberD",
        "Date": "12-Sep-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 134
    },
    {
        "FName": "FMemberE",
        "Date": "18-Sep-20",
        "accountId": "xx",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 135
    },
    {
        "FName": "FMemberF",
        "Date": "18-Sep-20",
        "accountId": "yy",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 136
    },
    {
        "FName": "FMemberC",
        "Date": "25-Sep-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1860,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 137
    },
    {
        "FName": "FMemberC",
        "Date": "25-Sep-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 138
    },
    {
        "FName": "FMemberC",
        "Date": "05-Oct-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 139
    },
    {
        "FName": "FMemberC",
        "Date": "05-Oct-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 140
    },
    {
        "FName": "FMemberA",
        "Date": "05-Oct-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1680,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 141
    },
    {
        "FName": "FMemberB",
        "Date": "05-Oct-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 2400,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 142
    },
    {
        "FName": "FMemberC",
        "Date": "10-Oct-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5240,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 143
    },
    {
        "FName": "FMemberD",
        "Date": "12-Oct-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 144
    },
    {
        "FName": "FMemberE",
        "Date": "18-Oct-20",
        "accountId": "xx",
        "aa": "Party",
        "aaa": "Birthday",
        "amount": 3320,
        "Mode of Payment": "Online Payment",
        "subType": "Party - Birthday",
        "type": "Expenditure",
        "id": 145
    },
    {
        "FName": "FMemberF",
        "Date": "18-Oct-20",
        "accountId": "yy",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 146
    },
    {
        "FName": "FMemberC",
        "Date": "25-Oct-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1950,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 147
    },
    {
        "FName": "FMemberC",
        "Date": "25-Oct-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 148
    },
    {
        "FName": "FMemberC",
        "Date": "05-Nov-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 149
    },
    {
        "FName": "FMemberC",
        "Date": "05-Nov-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 150
    },
    {
        "FName": "FMemberA",
        "Date": "05-Nov-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 2900,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 151
    },
    {
        "FName": "FMemberC",
        "Date": "05-Nov-20",
        "accountId": 332211,
        "aa": "Fuel",
        "aaa": "Car",
        "amount": 2790,
        "Mode of Payment": "Credit Card",
        "subType": "Fuel - Car",
        "type": "Expenditure",
        "id": 152
    },
    {
        "FName": "FMemberB",
        "Date": "05-Nov-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 1120,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 153
    },
    {
        "FName": "FMemberC",
        "Date": "10-Nov-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5870,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 154
    },
    {
        "FName": "FMemberD",
        "Date": "12-Nov-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 155
    },
    {
        "FName": "FMemberE",
        "Date": "18-Nov-20",
        "accountId": "xx",
        "aa": "Toys",
        "aaa": "Cycle",
        "amount": 5500,
        "Mode of Payment": "Online Payment",
        "subType": "Toys - Cycle",
        "type": "Expenditure",
        "id": 156
    },
    {
        "FName": "FMemberF",
        "Date": "18-Nov-20",
        "accountId": "yy",
        "aa": "Toys",
        "aaa": "Cycle",
        "amount": 4500,
        "Mode of Payment": "Online Payment",
        "subType": "Toys - Cycle",
        "type": "Expenditure",
        "id": 157
    },
    {
        "FName": "FMemberC",
        "Date": "25-Nov-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1990,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 158
    },
    {
        "FName": "FMemberC",
        "Date": "25-Nov-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 159
    },
    {
        "FName": "FMemberC",
        "Date": "05-Dec-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 160
    },
    {
        "FName": "FMemberC",
        "Date": "05-Dec-20",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 161
    },
    {
        "FName": "FMemberA",
        "Date": "05-Dec-20",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1900,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 162
    },
    {
        "FName": "FMemberB",
        "Date": "05-Dec-20",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 2590,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 163
    },
    {
        "FName": "FMemberC",
        "Date": "10-Dec-20",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5480,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 164
    },
    {
        "FName": "FMemberD",
        "Date": "12-Dec-20",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 165
    },
    {
        "FName": "FMemberE",
        "Date": "18-Dec-20",
        "accountId": "xx",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 166
    },
    {
        "FName": "FMemberF",
        "Date": "18-Dec-20",
        "accountId": "yy",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 167
    },
    {
        "FName": "FMemberC",
        "Date": "25-Dec-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 2030,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 168
    },
    {
        "FName": "FMemberC",
        "Date": "25-Dec-20",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 169
    },
    {
        "FName": "FMemberC",
        "Date": "05-Jan-21",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 170
    },
    {
        "FName": "FMemberC",
        "Date": "05-Jan-21",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 171
    },
    {
        "FName": "FMemberA",
        "Date": "05-Jan-21",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1860,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 172
    },
    {
        "FName": "FMemberB",
        "Date": "05-Jan-21",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 3850,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 173
    },
    {
        "FName": "FMemberC",
        "Date": "07-Jan-21",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 4460,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 174
    },
    {
        "FName": "FMemberD",
        "Date": "10-Jan-21",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 175
    },
    {
        "FName": "FMemberE",
        "Date": "18-Jan-21",
        "accountId": "xx",
        "aa": "Party",
        "aaa": "Birthday",
        "amount": 3320,
        "Mode of Payment": "Online Payment",
        "subType": "Party - Birthday",
        "type": "Expenditure",
        "id": 176
    },
    {
        "FName": "FMemberF",
        "Date": "18-Jan-21",
        "accountId": "yy",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 177
    },
    {
        "FName": "FMemberC",
        "Date": "25-Jan-21",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1970,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 178
    },
    {
        "FName": "FMemberC",
        "Date": "25-Jan-21",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 179
    },
    {
        "FName": "FMemberC",
        "Date": "05-Feb-21",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 180
    },
    {
        "FName": "FMemberC",
        "Date": "05-Feb-21",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 181
    },
    {
        "FName": "FMemberA",
        "Date": "05-Feb-21",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 1460,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 182
    },
    {
        "FName": "FMemberB",
        "Date": "05-Feb-21",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 4780,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 183
    },
    {
        "FName": "FMemberC",
        "Date": "07-Feb-21",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5360,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 184
    },
    {
        "FName": "FMemberC",
        "Date": "10-Feb-21",
        "accountId": 332211,
        "aa": "Fuel",
        "aaa": "Car",
        "amount": 6500,
        "Mode of Payment": "Credit Card",
        "subType": "Fuel - Car",
        "type": "Expenditure",
        "id": 185
    },
    {
        "FName": "FMemberD",
        "Date": "10-Feb-21",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 186
    },
    {
        "FName": "FMemberE",
        "Date": "18-Feb-21",
        "accountId": "xx",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 187
    },
    {
        "FName": "FMemberF",
        "Date": "18-Feb-21",
        "accountId": "yy",
        "aa": "NULL",
        "aaa": "NULL",
        "amount": "NULL",
        "Mode of Payment": "",
        "subType": "NULL - NULL",
        "type": "Expenditure",
        "id": 188
    },
    {
        "FName": "FMemberC",
        "Date": "25-Feb-21",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1980,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 189
    },
    {
        "FName": "FMemberC",
        "Date": "25-Feb-21",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 190
    },
    {
        "FName": "FMemberC",
        "Date": "05-Mar-21",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Home Lone",
        "amount": 50000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Home Lone",
        "type": "Expenditure",
        "id": 191
    },
    {
        "FName": "FMemberC",
        "Date": "05-Mar-21",
        "accountId": 332211,
        "aa": "EMI",
        "aaa": "Car Loan",
        "amount": 20000,
        "Mode of Payment": "Online Payment",
        "subType": "EMI - Car Loan",
        "type": "Expenditure",
        "id": 192
    },
    {
        "FName": "FMemberA",
        "Date": "05-Mar-21",
        "accountId": 112233,
        "aa": "Medicine",
        "aaa": "ABC Medical Store",
        "amount": 970,
        "Mode of Payment": "Debit Card",
        "subType": "Medicine - ABC Medical Store",
        "type": "Expenditure",
        "id": 193
    },
    {
        "FName": "FMemberB",
        "Date": "05-Mar-21",
        "accountId": 228899,
        "aa": "Groceries",
        "aaa": "Vegetables",
        "amount": 1590,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Vegetables",
        "type": "Expenditure",
        "id": 194
    },
    {
        "FName": "FMemberC",
        "Date": "07-Mar-21",
        "accountId": 332211,
        "aa": "Groceries",
        "aaa": "Provisions",
        "amount": 5550,
        "Mode of Payment": "PayTM",
        "subType": "Groceries - Provisions",
        "type": "Expenditure",
        "id": 195
    },
    {
        "FName": "FMemberD",
        "Date": "10-Mar-21",
        "accountId": 445566,
        "aa": "Accessories",
        "aaa": "Clothes",
        "amount": 1500,
        "Mode of Payment": "Cash",
        "subType": "Accessories - Clothes",
        "type": "Expenditure",
        "id": 196
    },
    {
        "FName": "FMemberE",
        "Date": "18-Mar-21",
        "accountId": "xx",
        "aa": "Clothes",
        "aaa": "Online",
        "amount": 1200,
        "Mode of Payment": "Credit Card",
        "subType": "Clothes - Online",
        "type": "Expenditure",
        "id": 197
    },
    {
        "FName": "FMemberF",
        "Date": "18-Mar-21",
        "accountId": "yy",
        "aa": "Clothes",
        "aaa": "Online",
        "amount": 1200,
        "Mode of Payment": "Credit Card",
        "subType": "Clothes - Online",
        "type": "Expenditure",
        "id": 198
    },
    {
        "FName": "FMemberC",
        "Date": "25-Mar-21",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Electricity",
        "amount": 1980,
        "Mode of Payment": "Online Payment",
        "subType": "Bill - Electricity",
        "type": "Expenditure",
        "id": 199
    },
    {
        "FName": "FMemberC",
        "Date": "25-Mar-21",
        "accountId": 332211,
        "aa": "Bill",
        "aaa": "Phone",
        "amount": 500,
        "Mode of Payment": "PayTM",
        "subType": "Bill - Phone",
        "type": "Expenditure",
        "id": 200
    },
    {
        "FName": "FMemberC",
        "subType": "Home Loan",
        "accountId": 337788,
        "amount": 50000,
        "Start Date": "02-Sep-17",
        "End Date": "02-Sep-27",
        "Rate of Interest": 7.5,
        "id": 201,
        "type": "Loan"
    },
    {
        "FName": "FmemberD",
        "subType": "Car Loan",
        "accountId": 447788,
        "amount": 20000,
        "Start Date": "05-Jun-20",
        "End Date": "05-Jun-25",
        "Rate of Interest": 8.5,
        "id": 202,
        "type": "Loan"
    },

    {
        "FName": "FMemberC",
        "Date": "01-01-2022",
        "accountId": '000000',
        "aa": "Earning",
        "aaa": "Electricity",
        "amount": 1980,
        "Mode of Payment": "Account",
        "subType": "Earning",
        "type": "Earning",
        "id": 203
    },
]